name: memmap
description: A Linux Dart API for memory mapped buffers.
version: 1.0.6

repository: https://github.com/tercen/memmap

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
